[connections.supabase] 
SUPABASE_URL="https://cfuoekvmmjfocmbbbljn.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdW9la3ZtbWpmb2NtYmJibGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDM2OTYsImV4cCI6MjA2NDE3OTY5Nn0.RA1yWcTWO2jY2jaSv1u0OADd8LTNseF8cwlmVgS70u0"